export const PHRASES = [
  "A felicidade é uma ilusão criada pelos programadores que nunca testaram seu código em produção.",
  "A programação é como a matemática, mas com mais bugs e menos certezas.",
  "A programação é para todos mas, as vagas são só para os programadores mais experientes.",
  "A única constante no código é o bug.",
  "Cada linha de código é uma oportunidade para um erro.",
  "Não desista de aprender a programar, mas também não se esforce muito, você provavelmente não vai se tornar um bom programador mesmo.",
  "Não desista de debugar, continue tentando. Mas não se iluda, vai dar tudo errado no final.",
  "Não importa quantas linhas de código você escreva, sempre haverá mais erros do que você pode corrigir.",
  "Não se preocupe em escrever um código perfeito, você nunca conseguirá mesmo.",
  "Não se preocupe em ter um código limpo, a vida é curta demais para isso.",
  "Não seja tão ambicioso com esse código, provavelmente não vai ficar bom mesmo.",
  "Nenhum código é à prova de falhas, mas alguns são mais falhos do que outros.",
  "Nunca confie em um código que parece funcionar na primeira vez.",
  "O que é sucesso na programação? Provavelmente algo que você nunca alcançará.",
  "O sucesso é relativo, o fracasso é garantido em todas as iterações.",
  "Programação é uma piada, e seu código é a piada mais engraçada de todas.",
  "Se a vida te der limões, provavelmente isso não é o suficiente para encontrar uma solução decente.",
  "Se você acha que seu código está perfeito, é porque você ainda não o testou.",
  "Se você não tem expectativas, não tem como se decepcionar com o desempenho do seu código.",
  "Se você quer algo bem feito, faça você mesmo. Mas provavelmente vai dar errado.",
  "Seja realista: se você nunca conseguiu programar isso antes, por que conseguiria agora?",
  "Sempre que há uma solução simples para um problema de programação, ela está errada.",
  "Seu código é um fracasso, mas pelo menos ele é consistente.",
];
